// New hood geometry comes ONLY from the new raster sources below. Existing
// regular hoods supply the garment's attachment seam, never the new crown/opening.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { sharp, fits, readAsset, assetPath, rawSvg, inner, tint } from './hood_render.mjs';
const require = createRequire(import.meta.url);
const potrace = require('potrace');
export const W = 2048;
export const ROOT = 'src/assets/studio-hoodie/hoods/rebuilt';
export const variants = [
  { id: 'scuba', file: 'Scuba hood', label: 'Scuba Hood', aspect: 0.96 },
  { id: 'funnel-hood-hybrid', file: 'Funnel-hood hybrid', label: 'Funnel Hybrid Hood', aspect: 1.02 },
];
export const hash = (data) => crypto.createHash('sha256').update(data).digest('hex');
export function layer(svg, index) {
  const groups = [...svg.matchAll(/<g\b[^>]*>[\s\S]*?<\/g>/g)];
  if (groups.length !== 2) throw new Error('Expected separate fabric and ink groups');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="2048" height="2048" viewBox="0 0 2048 2048">${groups[index][0]}</svg>`;
}
export const alpha = (raw) => Uint8Array.from({ length: W * W }, (_, i) => raw[i * 4 + 3]);
export function profile(mask) {
  const bottom = new Int32Array(W).fill(-1);
  let left = W, right = -1, top = W, maxY = -1;
  for (let y = 0; y < W; y++) for (let x = 0; x < W; x++) {
    if (mask[y * W + x] < 128) continue;
    bottom[x] = y; left = Math.min(left, x); right = Math.max(right, x);
    top = Math.min(top, y); maxY = Math.max(maxY, y);
  }
  if (right < left) throw new Error('Empty mask');
  return { bottom, left, right, top, maxY };
}
export function neckline(mask) {
  const p = profile(mask);
  const minimum = p.maxY - (p.right - p.left) * 0.28;
  while (p.bottom[p.left] < minimum) p.left++;
  while (p.bottom[p.right] < minimum) p.right--;
  return p;
}
function silhouette(ink) {
  const exterior = new Uint8Array(W * W), queue = new Int32Array(W * W);
  let head = 0, tail = 0;
  const add = (i) => { if (!exterior[i] && ink[i] < 128) { exterior[i] = 1; queue[tail++] = i; } };
  for (let n = 0; n < W; n++) { add(n); add((W - 1) * W + n); add(n * W); add(n * W + W - 1); }
  while (head < tail) {
    const i = queue[head++], x = i % W;
    if (x) add(i - 1); if (x < W - 1) add(i + 1);
    if (i >= W) add(i - W); if (i < W * (W - 1)) add(i + W);
  }
  return Uint8Array.from(exterior, (v) => v ? 0 : 255);
}
function sample(a, x, y) {
  const x0 = Math.floor(x), y0 = Math.floor(y), fx = x - x0, fy = y - y0;
  const at = (xx, yy) => xx < 0 || yy < 0 || xx >= W || yy >= W ? 0 : a[yy * W + xx];
  return (at(x0, y0) * (1 - fx) + at(x0 + 1, y0) * fx) * (1 - fy)
    + (at(x0, y0 + 1) * (1 - fx) + at(x0 + 1, y0 + 1) * fx) * fy;
}
function interiorDistance(mask) {
  const d = Uint16Array.from(mask, (v) => v >= 128 ? W : 0);
  for (let y = 0; y < W; y++) for (let x = 0; x < W; x++) {
    const i = y * W + x;
    if (d[i]) d[i] = Math.min(d[i], x ? d[i - 1] + 1 : 1, y ? d[i - W] + 1 : 1);
  }
  for (let y = W - 1; y >= 0; y--) for (let x = W - 1; x >= 0; x--) {
    const i = y * W + x;
    if (d[i]) d[i] = Math.min(d[i], x < W - 1 ? d[i + 1] + 1 : 1, y < W - 1 ? d[i + W] + 1 : 1);
  }
  return d;
}
async function trace(mask) {
  const box = profile(mask);
  const left = Math.max(0, box.left - 3), top = Math.max(0, box.top - 3);
  const width = Math.min(W - left, box.right - left + 4), height = Math.min(W - top, box.maxY - top + 4);
  // Node Potrace blackOnWhite explicitly sets ink polarity; the Python Bitmap
  // constructor inversion does not apply to this implementation.
  const png = await sharp(Buffer.from(mask), { raw: { width: W, height: W, channels: 1 } })
    .extract({ left, top, width, height }).negate().resize(width * 3, height * 3, { kernel: 'lanczos3' }).threshold(128).png().toBuffer();
  const svg = await new Promise((resolve, reject) => potrace.trace(png, {
    turdSize: 4, turnPolicy: potrace.Potrace.TURNPOLICY_MINORITY, alphaMax: 1,
    optCurve: true, optTolerance: 0.2, threshold: 128, blackOnWhite: true, color: '#000000',
  }, (error, result) => error ? reject(error) : resolve(result)));
  const d = svg.match(/<path[^>]*d="([^"]+)"/)[1];
  // Convert only coordinates already generated by Potrace to builder units.
  return d.replace(/([MLC])([^MLCZ]*)/gi, (_, cmd, numbers) => {
    const values = numbers.trim().split(/[\s,]+/).filter(Boolean).map(Number);
    return cmd + values.map((v, i) => (i % 2 ? (W - top - v / 3) * 10 : (left + v / 3) * 10).toFixed(2)).join(' ');
  });
}
function wrap(title, fill, ink) {
  const group = 'transform="translate(0,2048) scale(0.1,-0.1)"';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="2048" height="2048" viewBox="0 0 2048 2048">\n<title>${title}</title>\n<g ${group} fill="#000000" stroke="none"><path d="${fill}" fill-rule="evenodd"/></g>\n<g ${group} fill="#141414" stroke="none"><path d="${ink}" fill="#141414" fill-rule="evenodd"/></g>\n</svg>\n`;
}
export function candidate(variant, fit) { return `${ROOT}/${variant.id}/fits/${fit}.svg`; }
export function compositeCandidate(variant, fit, coloured = true) {
  const parts = ['Left sleeve', 'Right sleeve', 'Body', 'Rib hem', 'Left cuff', 'Right cuff', 'Hood', 'Kangaroo pocket'];
  const colours = ['#9cb6c7', '#9cb6c7', '#e4ddd0', '#81989a', '#b5a4d7', '#b5a4d7', variant.id === 'scuba' ? '#e97766' : '#83b7a0', '#e4ddd0'];
  return `<svg xmlns="http://www.w3.org/2000/svg" width="2048" height="2048" viewBox="0 0 2048 2048">${parts.map((part, i) => inner(tint(part === 'Hood' ? fs.readFileSync(candidate(variant, fit), 'utf8') : readAsset(part, fit), coloured ? colours[i] : '#ffffff'))).join('')}</svg>`;
}
export async function rebuildHoods(only) {
  for (const variant of variants.filter((entry) => !only || entry.id === only)) {
    const dir = `${ROOT}/${variant.id}`;
    fs.mkdirSync(`${dir}/fits`, { recursive: true });
    fs.mkdirSync(`${dir}/proofs`, { recursive: true });
    const sourceBytes = fs.readFileSync(`${dir}/source.png`);
    const raw = await sharp(sourceBytes).resize(W, W).flatten({ background: 'white' }).removeAlpha().raw().toBuffer();
    const ink = new Uint8Array(W * W);
    for (let i = 0; i < ink.length; i++) {
      const lum = 0.2126 * raw[i * 3] + 0.7152 * raw[i * 3 + 1] + 0.0722 * raw[i * 3 + 2];
      const contrast = Math.max(0, Math.min(255, (lum - 128) * 1.35 + 128));
      ink[i] = Math.round(255 * Math.max(0, Math.min(1, (246 - contrast) / 126)));
    }
    const fill = silhouette(ink), src = profile(fill);
    const sourceDistance = interiorDistance(fill);
    const innerInk = Uint8Array.from(ink, (v, i) => sourceDistance[i] > 12 ? v : 0);
    const area = fill.reduce((s, v) => s + (v >= 128), 0);
    if (area < (src.right - src.left) * (src.maxY - src.top) * 0.45) throw new Error(`${variant.id}: open raster silhouette`);
    const keyed = Buffer.alloc(W * W * 4);
    for (let i = 0; i < ink.length; i++) keyed[i * 4 + 3] = ink[i];
    await sharp(keyed, { raw: { width: W, height: W, channels: 4 } }).png().toFile(`${dir}/keyed-lineart.png`);
    fs.writeFileSync(`${dir}/source-lineart.svg`, wrap(`${variant.label} - new raster trace`, '', await trace(ink)));
    const manifest = { variant: variant.id, label: variant.label, source: 'source.png', sourceSha256: hash(sourceBytes), rasterFirst: true, oldVariantGeometryUsed: false, fits: {} };
    const tiles = [];
    for (const fit of fits) {
      const regular = readAsset('Hood', fit);
      const regularFill = alpha(await rawSvg(layer(regular, 0), W));
      const regularInk = alpha(await rawSvg(layer(regular, 1), W));
      const target = neckline(alpha(await rawSvg(regular, W)));
      const body = alpha(await rawSvg(readAsset('Body', fit), W));
      const nextFill = new Uint8Array(W * W), nextInk = new Uint8Array(W * W);
      const width = target.right - target.left;
      // Size against the neckline/shoulders, not the height of the old hood.
      const height = width * variant.aspect;
      const top = target.maxY - height;
      for (let x = target.left; x <= target.right; x++) {
        const sx = src.left + (x - target.left) / width * (src.right - src.left);
        const sx0 = Math.floor(sx), sx1 = Math.min(W - 1, sx0 + 1), fraction = sx - sx0;
        const sourceBottom = src.bottom[sx0] * (1 - fraction) + src.bottom[sx1] * fraction;
        const bottom = target.bottom[x];
        for (let y = Math.max(0, Math.floor(top)); y <= bottom; y++) {
          const sy = src.top + (y - top) / (bottom - top) * (sourceBottom - src.top);
          const i = y * W + x;
          nextFill[i] = Math.round(sample(fill, sx, sy));
          nextInk[i] = Math.round(sample(innerInk, sx, sy));
          if (y >= bottom - 4) {
            nextFill[i] = Math.max(regularFill[i], regularInk[i]);
            nextInk[i] = regularInk[i];
          }
          if (body[i] >= 128) nextFill[i] = 0;
        }
      }
      if (variant.id === 'scuba') {
        // A compact upright scuba side panel has no exterior notches. Close
        // the column slivers caused by seating the source's narrow base.
        for (let x = target.left; x <= target.right; x++) {
          let roof = Math.max(0, Math.floor(top));
          while (roof < target.bottom[x] && nextFill[roof * W + x] < 128) roof++;
          for (let y = roof; y <= target.bottom[x]; y++) {
            const i = y * W + x;
            if (body[i] < 128) nextFill[i] = 255;
          }
        }
      }
      // Derive a continuous two-pixel construction outline from the adapted
      // raster boundary; source exterior ink is not stretched into fold marks.
      const distance = interiorDistance(nextFill);
      for (let i = 0; i < distance.length; i++) {
        if (distance[i] > 0 && distance[i] <= 2) nextInk[i] = 255;
      }
      const svg = wrap(`${fit} - ${variant.label}`, await trace(nextFill), await trace(nextInk));
      fs.writeFileSync(candidate(variant, fit), svg);
      manifest.fits[fit] = {
        regularSha256: hash(regular), bodySha256: hash(readAsset('Body', fit)),
        necklineLeft: target.left, necklineRight: target.right, bottom: target.maxY,
        crownTop: Math.round(top), heightToWidth: variant.aspect, candidateSha256: hash(svg),
      };
      await sharp(Buffer.from(compositeCandidate(variant, fit))).flatten({ background: 'white' }).png().toFile(`${dir}/proofs/${fit}.png`);
      tiles.push({ input: await sharp(Buffer.from(compositeCandidate(variant, fit))).resize(410, 410).png().toBuffer(), left: fits.indexOf(fit) * 410, top: 0 });
      console.log(`${variant.label} / ${fit}: NEW raster traced; ${width}px width x ${Math.round(height)}px height`);
    }
    await sharp({ create: { width: 2050, height: 410, channels: 4, background: 'white' } }).composite(tiles).png().toFile(`${dir}/proofs/all-fits.png`);
    fs.writeFileSync(`${dir}/registration.json`, JSON.stringify(manifest, null, 2) + '\n');
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) await rebuildHoods();
