import { strict as assert } from 'node:assert';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { createGarmentRegressionFixture } from '../../src/app/data/garmentRegressionFixtures';
import { canAcceptImportedConstruction, importedControlGroups, importedGarmentLayers, mergeImportedGarmentView, normalizeImportedGarment, recolorImportedParts, type ImportedGarment, type ImportedPart } from '../../src/app/data/importedGarment';
import { separateConstructionControls, constructionNeedsReview, constructionRegionsForView, linkConstructionRegions, mergeConstructionRegions, patchConstructionRegion, reviewConstructionRegions, splitConstructionRegion, type ConstructionRegion, type ConstructionRegions } from '../../src/app/data/importedConstructionRegions';
import { ImportedConstructionRegionReview } from '../../src/app/components/builder/ImportedConstructionRegionReview';
import { ImportedGarmentEditor } from '../../src/app/components/builder/ImportedGarmentEditor';
import { renderTexturedFabricSvg } from '../../src/app/lib/fabricRendering';
import { convertImportedZip, importedZipClosures, reviewImportedZip, type ImportedZipClosure } from '../../src/app/data/importedClosures';
import { ImportedClosureControls } from '../../src/app/components/builder/ImportedClosureControls';

const ink = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M10 10L1900 1900" stroke="black"/></svg>';
function fixture(view: 'front' | 'back' = 'front'): ImportedGarment {
  const source = createGarmentRegressionFixture('tee');
  const region = (suffix: string, path: string, label: string): ConstructionRegion => ({ id: `${view}-${suffix}`, label, semanticType: 'body', builderCategory: 'fabric-colour',
    view, path, confidence: .62, parentRegionId: null, mirroredPairId: null, colourGroupId: '', fabricGroupId: '', editableIndependently: true, zIndex: 1 });
  const upper = region('upper', 'M100 100L900 100L900 500L100 500Z', 'Upper chest panel');
  const lower = region('lower', 'M100 500L900 500L900 900L100 900Z', 'Lower body panel');
  const data: ConstructionRegions = { version: 1, status: 'needs-review', regions: [upper, lower], constructionInk: ink, stitchingPaths: [], hardware: [], closures: [], seams: [], warnings: ['Check chest seam.'] };
  const template = source.parts.find(part => part.layerKind === 'structural')!;
  const parts: ImportedPart[] = data.regions.map(item => ({ ...template, id: item.id, view, name: item.label, layerOrder: item.zIndex, semanticType: 'body',
    boundary: { boundaryType: 'seam', confidence: item.confidence, evidence: 'Local source-boundary candidate' },
    svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="${item.path}"/></svg>` }));
  parts.push({ ...template, id: `${view}-source-ink`, view, structuralRole: 'source-ink', colorable: false, svg: ink, constructionSvg: ink, layerOrder: 1000 });
  return normalizeImportedGarment({ ...source, processingMode: 'trace-only', parts, detailLayers: [], constructionRegions: data, lineArtSvg: ink,
    manifest: { ...source.manifest, view, frontView: undefined, backView: undefined }, sourceManifest: { ...source.sourceManifest, view, regions: parts }, accepted: false });
}
const front = fixture(), pristine = front.parts.find(part => part.structuralRole === 'source-ink')!;
const sleeveParent = patchConstructionRegion(front, 'front', 'front-upper', { semanticType: 'sleeve', builderCategory: 'sleeves' });
constructionRegionsForView(sleeveParent, 'front')!.regions[1].parentRegionId = 'front-upper';
const sleeveInset = patchConstructionRegion(sleeveParent, 'front', 'front-lower', { semanticType: 'panel', builderCategory: 'custom-details' });
assert.equal(constructionRegionsForView(sleeveInset, 'front')!.regions[1].builderCategory, 'sleeves');
assert.equal(sleeveInset.parts[1].builderCategory, 'sleeves', 'Saved curved sleeve insets route to Sleeves');
assert.equal(sleeveInset.parts[1].colourGroup, front.parts[1].colourGroup);
assert.equal(sleeveInset.parts[1].fabricGroup, front.parts[1].fabricGroup);
assert.equal(constructionRegionsForView(sleeveInset, 'front')!.regions[1].path, constructionRegionsForView(front, 'front')!.regions[1].path);
assert.strictEqual(sleeveInset.parts.find(part => part.id === pristine.id), pristine);
const pocket = patchConstructionRegion(front, 'front', 'front-lower', { semanticType: 'pocket', builderCategory: 'fabric-colour' });
assert.equal(constructionRegionsForView(pocket, 'front')!.regions[1].builderCategory, 'pockets-zips');
assert.equal(pocket.parts[1].builderCategory, 'pockets-zips', 'Kangaroo pockets belong to Openings & Closures, not the body');
assert.equal(pocket.parts[0].builderCategory, 'fabric-colour', 'The lower body remains separate from the pocket');
assert.ok(importedControlGroups(pocket, true).some(group => group.category === 'pockets-zips'));
const drawstring = patchConstructionRegion(front, 'front', 'front-lower', { semanticType: 'drawstring', builderCategory: 'trims-details' });
assert.equal(importedGarmentLayers(drawstring, 'front').find(layer => layer.id === 'front-lower')!.fabricRegion, undefined);
assert.equal(drawstring.parts[1].colorable, true, 'Source-derived drawstrings are colourable trim');
assert.equal(importedGarmentLayers(drawstring, 'front', { 'front-lower': '#abc123' }).find(layer => layer.id === 'front-lower')!.tint, '#abc123');
const button = patchConstructionRegion(front, 'front', 'front-lower', { semanticType: 'button', builderCategory: 'trims-details' });
assert.equal(button.parts[1].colorable, true, 'Source-derived hardware surfaces can be recoloured');
assert.equal(importedGarmentLayers(button, 'front').find(layer => layer.id === 'front-lower')!.fabricRegion, undefined);
const zip: ImportedZipClosure = { id: 'front-zip', label: 'Centre zip', view: 'front', semanticType: 'zip', maskPath: 'M995 100H1005V900H995Z',
  start: { x: 1000, y: 100 }, end: { x: 1000, y: 900 }, width: 10, status: 'needs-review' };
let zipGarment = fixture();
constructionRegionsForView(zipGarment, 'front')!.closures = [zip, { id: 'legacy-unisolated-zip', semanticType: 'zip' }];
assert.equal(importedZipClosures(zipGarment, 'front').length, 1, 'Unisolated legacy hardware is not falsely editable');
assert.equal(importedGarmentLayers(zipGarment, 'front').some(layer => layer.id === zip.id), false, 'Isolation must be reviewed first');
assert.throws(() => convertImportedZip(zip, []), /Review/);
zipGarment = reviewImportedZip(zipGarment, 'front', zip.id, true);
const reviewedZip = importedZipClosures(zipGarment, 'front')[0];
const zipLayers = importedGarmentLayers(zipGarment, 'front', { [zip.id]: '#ff0000' });
assert.equal(zipLayers.find(layer => layer.id === zip.id)!.tint, '#ff0000');
assert.ok(zipLayers.find(layer => layer.id === pristine.id)!.svgRaw.includes('zip-source-mask'));
assert.equal(zipGarment.parts.find(part => part.id === pristine.id)!.svg, ink, 'Original stored ink remains immutable');
assert.equal(constructionRegionsForView(zipGarment, 'front')!.constructionInk, ink);
assert.equal(importedGarmentLayers(zipGarment, 'back').some(layer => layer.id === zip.id), false);
const convertedZip = convertImportedZip(reviewedZip, [], '#112233');
assert.deepEqual(convertedZip[0].opening!.start, zip.start);
assert.deepEqual(convertedZip[0].opening!.end, zip.end);
assert.equal(convertedZip[0].opening!.width, zip.width);
assert.equal(convertedZip[0].zipTeethColor, '#112233');
assert.equal(convertImportedZip(reviewedZip, convertedZip).length, 1, 'Repeated conversion selects the existing replacement');
assert.equal(importedGarmentLayers(zipGarment, 'front', {}, convertedZip).some(layer => layer.id === zip.id), false);
assert.ok(importedGarmentLayers(zipGarment, 'front', {}, [{ ...convertedZip[0], hidden: true }]).some(layer => layer.id === zip.id), 'Hidden or deleted replacement restores original zip');
assert.ok(importedGarmentLayers(zipGarment, 'front', {}, []).some(layer => layer.id === zip.id));
const zipControls = renderToStaticMarkup(createElement(ImportedClosureControls, { garment: zipGarment, view: 'front', onChange: () => {}, onColor: () => {}, onConvert: () => {}, onRestore: () => {} }));
assert.ok(zipControls.includes('Convert to editable zip'));
assert.deepEqual(recolorImportedParts(zipGarment, zip.id, '#556677', 'part', { 'front-lower': '#aabbcc' }), { 'front-lower': '#aabbcc', [zip.id]: '#556677' });
assert.ok(canAcceptImportedConstruction(front), 'Lower confidence source-derived regions are reviewable');
const legacy = { ...front, constructionRegions: undefined, manifest: { ...front.manifest, frontView: { ...front.manifest.frontView!, constructionRegions: undefined } } };
assert.equal(canAcceptImportedConstruction(legacy), false, 'Legacy confidence validation must not be weakened');
assert.equal(constructionNeedsReview(front), true);
assert.notEqual(front.parts[0].colourGroup, front.parts[1].colourGroup, 'Chest panels remain independently grouped');
assert.ok(!importedControlGroups(front).some(group => group.parts.some(part => part.id === pristine.id)), 'Ink is not a category control');
let corrected = patchConstructionRegion(front, 'front', 'front-upper', { label: 'Chest yoke', semanticType: 'yoke', builderCategory: 'fabric-colour', fabricGroupId: 'nylon' });
assert.equal(corrected.parts[0].name, 'Chest yoke');
assert.equal(corrected.parts[0].fabricGroup, 'nylon');
assert.equal(corrected.parts[0].colourGroup, front.parts[0].colourGroup, 'Fabric groups do not change colour groups');
assert.equal(corrected.parts[0].boundary?.confidence, .62, 'Review never inflates confidence');
assert.strictEqual(corrected.parts.find(part => part.id === pristine.id), pristine);
assert.equal(corrected.lineArtSvg, front.lineArtSvg);
assert.throws(() => patchConstructionRegion(front, 'front', pristine.id, { label: 'Ink edited' }));
corrected = patchConstructionRegion(corrected, 'front', 'front-upper', { decorative: true });
assert.equal(corrected.parts[0].colorable, false);
corrected = patchConstructionRegion(corrected, 'front', 'front-upper', { decorative: false });
assert.equal(corrected.parts[0].colorable, true);
const linked = linkConstructionRegions(front, 'front', 'front-upper', 'front-lower');
assert.equal(linked.parts[0].symmetryPartner, 'front-lower');
assert.equal(linked.parts[1].symmetryPartner, 'front-upper');
assert.equal(linked.parts[0].colourGroup, linked.parts[1].colourGroup);
assert.equal(linked.parts[0].fabricGroup, linked.parts[1].fabricGroup);
assert.notEqual(linked.parts[0].colourGroup, linked.parts[0].fabricGroup);
assert.deepEqual(recolorImportedParts(linked, 'front-upper', '#abcdef', 'group'), { 'front-upper': '#abcdef', 'front-lower': '#abcdef' });
assert.ok(linked.parts.slice(0, 2).every(part => part.editableIndependently), 'Colour links keep independent geometry editing');
assert.equal(importedControlGroups(linked, true).length, 1, 'Linked semantic colours have one control');
assert.equal(importedControlGroups(linked).length, 2, 'Linked colours do not merge the construction geometry');
let linkedPockets = linked;
for (const id of ['front-upper', 'front-lower']) linkedPockets = patchConstructionRegion(linkedPockets, 'front', id, { semanticType: 'pocket', builderCategory: 'pockets-zips' });
linkedPockets = { ...linkedPockets, accepted: true, reviewed: true };
const separatePockets = separateConstructionControls(linkedPockets, 'front', 'front-upper');
assert.equal(separatePockets.accepted, true);
assert.equal(separatePockets.reviewed, true);
assert.equal(importedControlGroups(separatePockets, true).length, 2);
assert.notEqual(separatePockets.parts[0].fabricGroup, separatePockets.parts[1].fabricGroup);
assert.equal(separatePockets.parts[0].symmetryPartner, linkedPockets.parts[0].symmetryPartner);
assert.deepEqual(constructionRegionsForView(separatePockets, 'front')!.regions.map(region => region.path), constructionRegionsForView(linkedPockets, 'front')!.regions.map(region => region.path));
assert.equal(constructionRegionsForView(separatePockets, 'front')!.constructionInk, ink);
assert.deepEqual(recolorImportedParts(separatePockets, 'front-upper', '#123456', 'group', { 'front-lower': '#abcdef' }), { 'front-upper': '#123456', 'front-lower': '#abcdef' });
const pocketControls = renderToStaticMarkup(createElement(ImportedGarmentEditor, { value: linkedPockets, onChange: () => {}, selectedId: null, onSelect: () => {}, onColor: () => {}, step: 6 }));
assert.ok(pocketControls.includes('Edit separately'), 'Linked pockets expose independent controls in Openings & Closures');
let hoodGroup = linked;
for (const id of ['front-upper', 'front-lower']) hoodGroup = patchConstructionRegion(hoodGroup, 'front', id, { semanticType: 'lining', builderCategory: 'neck-hood' });
assert.equal(importedControlGroups(hoodGroup, true)[0].name, 'Inner hood');
assert.equal(importedControlGroups(hoodGroup, true)[0].parts.length, 2);
let hemGroup = linked;
for (const id of ['front-upper', 'front-lower']) hemGroup = patchConstructionRegion(hemGroup, 'front', id, { semanticType: 'hem', builderCategory: 'hem-cuffs' });
assert.equal(importedControlGroups(hemGroup, true)[0].name, 'Bottom hem');
assert.equal(importedControlGroups(hemGroup, true)[0].parts.length, 2);
assert.equal(importedControlGroups(linkConstructionRegions(hoodGroup, 'front', 'front-upper', null), true).length, 2, 'Explicit unlinking still separates colour controls');
assert.deepEqual(recolorImportedParts(front, 'front-upper', '#abcdef', 'group'), { 'front-upper': '#abcdef' }, 'Unlinked upper/lower panels stay separate');
const staleAliases = { ...linked, parts: linked.parts.map(part => ({ ...part, colourGroup: part.id })) };
assert.deepEqual(recolorImportedParts(staleAliases, 'front-upper', '#abcdef', 'group'), { 'front-upper': '#abcdef', 'front-lower': '#abcdef' }, 'Semantic grouping uses region IDs, not stale part aliases');
const fabricOnlyLink = patchConstructionRegion(linked, 'front', 'front-lower', { colourGroupId: 'separate-lower' });
assert.deepEqual(recolorImportedParts(fabricOnlyLink, 'front-upper', '#abcdef', 'group'), { 'front-upper': '#abcdef' }, 'Fabric links do not imply colour links');
const frontLayers = importedGarmentLayers(front, 'front', { [pristine.id]: '#ff0000' });
assert.deepEqual(frontLayers.find(layer => layer.id === 'front-upper')?.fabricRegion, { role: 'body' }, 'Unlinked regions omit fabric group');
assert.equal(frontLayers.find(layer => layer.id === pristine.id)?.fabricRegion, undefined);
assert.equal(frontLayers.find(layer => layer.id === pristine.id)?.tint, undefined, 'Source ink has no tint');
assert.equal(frontLayers.find(layer => layer.id === pristine.id)?.washable, false);
const whiteSaved = { ...front, parts: front.parts.map(part => part.id === 'front-upper' ? { ...part, svg: part.svg.replace('fill="#000000"', 'fill="#ffffff"') } : part) };
const tintedLayer = importedGarmentLayers(whiteSaved, 'front', { 'front-upper': '#3e1919' }).find(layer => layer.id === 'front-upper')!;
assert.ok(renderTexturedFabricSvg(tintedLayer.svgRaw, tintedLayer.tint!, undefined, 'plain-region').includes('fill="#3e1919"'), 'Saved white semantic fills respond to colour without a fabric assignment');
assert.equal(normalizeImportedGarment(whiteSaved).parts[0].svg, front.parts[0].svg, 'Reload canonicalizes editable fills without changing their paths');
assert.strictEqual(normalizeImportedGarment(whiteSaved).parts.find(part => part.id === pristine.id), pristine, 'Canonicalizing fills leaves source ink untouched');
assert.deepEqual(frontLayers.find(layer => layer.id === pristine.id)?.colourPanels, []);
assert.ok(importedGarmentLayers(legacy, 'front').every(layer => !layer.fabricRegion), 'Legacy parts never opt in');
const linkedLayers = importedGarmentLayers(linked, 'front');
assert.equal(linkedLayers.find(layer => layer.id === 'front-upper')?.fabricRegion?.group, linked.constructionRegions!.regions[0].fabricGroupId);
assert.equal(linkedLayers.find(layer => layer.id === 'front-lower')?.fabricRegion?.group, linked.constructionRegions!.regions[0].fabricGroupId);
const lining = patchConstructionRegion(front, 'front', 'front-upper', { semanticType: 'lining' });
assert.deepEqual(importedGarmentLayers(lining, 'front').find(layer => layer.id === 'front-upper')?.fabricRegion, { role: 'lining', interior: true });
for (const semanticType of ['button', 'rivet', 'zip', 'label', 'decoration'] as const) {
  const excluded = patchConstructionRegion(front, 'front', 'front-upper', { semanticType });
  assert.equal(importedGarmentLayers(excluded, 'front').find(layer => layer.id === 'front-upper')?.fabricRegion, undefined, semanticType);
}
for (const patch of [{ decorative: true }, { editableIndependently: false }]) {
  const excluded = patchConstructionRegion(front, 'front', 'front-upper', patch);
  assert.equal(importedGarmentLayers(excluded, 'front').find(layer => layer.id === 'front-upper')?.fabricRegion, undefined);
}
assert.deepEqual(recolorImportedParts(front, pristine.id, '#abcdef', 'material'), {}, 'Ink cannot initiate colour changes');
assert.ok(!(pristine.id in recolorImportedParts(front, 'front-upper', '#abcdef', 'material')), 'Ink cannot receive grouped colour changes');
const unlinked = linkConstructionRegions(linked, 'front', 'front-upper', null);
assert.equal(unlinked.parts[1].symmetryPartner, null);
assert.notEqual(unlinked.parts[0].colourGroup, unlinked.parts[1].colourGroup);
const merged = mergeConstructionRegions(front, 'front', 'front-upper', 'front-lower');
assert.equal(merged.constructionRegions?.regions.length, 1);
assert.equal(merged.constructionRegions?.regions[0].id, 'front-upper', 'Merge preserves the selected target identity');
assert.equal(merged.parts.find(part => part.id === 'front-upper')?.color, front.parts[0].color, 'Merge keeps target colour');
assert.strictEqual(merged.parts.find(part => part.id === pristine.id), pristine);
const seamData = { ...merged.constructionRegions!, seams: [{ id: 'chest-seam', label: 'Source chest join', regionId: 'front-upper', parts: front.constructionRegions!.regions }] };
const withSeam = normalizeImportedGarment({ ...merged, constructionRegions: seamData, manifest: { ...merged.manifest, frontView: { ...merged.manifest.frontView!, constructionRegions: seamData } } });
assert.throws(() => splitConstructionRegion(withSeam, 'front', 'front-upper', 'invented'));
const split = splitConstructionRegion(withSeam, 'front', 'front-upper', 'chest-seam');
assert.equal(split.constructionRegions?.regions.length, 2);
const colouredSplit = splitConstructionRegion({ ...withSeam, parts: withSeam.parts.map(part => part.id === 'front-upper' ? { ...part, color: '#345678' } : part) }, 'front', 'front-upper', 'chest-seam');
assert.ok(colouredSplit.parts.filter(part => part.id !== pristine.id).every(part => part.color === '#345678'), 'Split children inherit the selected parent colour');
assert.strictEqual(split.parts.find(part => part.id === pristine.id), pristine);
assert.deepEqual(split.constructionRegions?.regions.map(region => region.path), front.constructionRegions?.regions.map(region => region.path));
const badSeam = { ...seamData, seams: [{ ...seamData.seams[0], parts: seamData.seams[0].parts.map(region => ({ ...region, path: 'M1 1L2 1L2 2L1 2Z' })) }] };
assert.throws(() => splitConstructionRegion({ ...withSeam, constructionRegions: badSeam, manifest: { ...withSeam.manifest, frontView: { ...withSeam.manifest.frontView!, constructionRegions: badSeam } } }, 'front', 'front-upper', 'chest-seam'), /partition/);
const candidateData: ConstructionRegions = { ...merged.constructionRegions!, regions: merged.constructionRegions!.regions.map(region => ({ ...region, candidateIds: ['front-cell-001', 'front-cell-002'] })),
  candidates: front.constructionRegions!.regions.map((region, index) => ({ id: `front-cell-00${index + 1}`, label: String(index + 1), path: region.path, bounds: [0, 0, 1, 1], area: 320000, confidence: .7, regionId: 'front-upper' })) };
const candidateGarment = normalizeImportedGarment({ ...merged, constructionRegions: candidateData, manifest: { ...merged.manifest, frontView: { ...merged.manifest.frontView!, constructionRegions: candidateData } } });
const cellSplit = splitConstructionRegion(candidateGarment, 'front', 'front-upper', 'front-cell-001');
assert.equal(cellSplit.constructionRegions?.regions.length, 2, 'Backend raw candidate can split along an evidenced cell boundary');
assert.equal(cellSplit.constructionRegions?.regions.find(region => region.id === 'front-cell-001-region')?.path, candidateData.candidates![0].path);
assert.equal(cellSplit.constructionRegions?.candidates?.[0].regionId, 'front-cell-001-region');
assert.strictEqual(cellSplit.parts.find(part => part.id === pristine.id), pristine);
assert.throws(() => splitConstructionRegion(cellSplit, 'front', 'front-cell-001-region', 'front-cell-001'), /two non-empty/);
const candidateMarkup = renderToStaticMarkup(createElement(ImportedConstructionRegionReview, { value: candidateGarment, view: 'front', selectedId: 'front-upper', onSelect() {}, onChange() {} }));
assert.match(candidateMarkup, /Source cell boundary 1/);
const combined = mergeImportedGarmentView(reviewConstructionRegions(corrected, 'front'), fixture('back'), 'back');
assert.equal(constructionRegionsForView(combined, 'front')?.status, 'reviewed');
const legacySources = { ...combined, sourceManifest: { ...combined.sourceManifest, frontView: undefined, backView: undefined,
  regions: [{ ...front.sourceManifest.regions[0], id: 'original-chest', view: undefined },
    ...combined.sourceManifest.regions.filter(region => region.view === 'back')] } };
const legacyBefore = JSON.stringify(legacySources);
const reanalysed = mergeImportedGarmentView(legacySources, legacySources, 'front');
assert.equal(reanalysed.sourceManifest.regions.filter(region => region.id === 'original-chest').length, 1, 'Re-analysis replaces legacy source evidence instead of duplicating it');
assert.equal(reanalysed.sourceManifest.regions.find(region => region.id === 'original-chest')?.view, 'front');
assert.deepEqual(reanalysed.parts, [...legacySources.parts.filter(part => part.view === 'back'), ...legacySources.parts.filter(part => part.view === 'front')]);
assert.deepEqual(reanalysed.manifest.backView, legacySources.manifest.backView, 'Re-analysis preserves the other view and its construction');
assert.equal(JSON.stringify(legacySources), legacyBefore, 'Resolving legacy source ownership does not mutate the input');
const repeated = mergeImportedGarmentView(JSON.parse(JSON.stringify(reanalysed)), reanalysed, 'front');
assert.deepEqual(repeated.sourceManifest.regions, reanalysed.sourceManifest.regions, 'Repeated analysis after reload is stable');
const backReplacement = mergeImportedGarmentView(legacySources, fixture('back'), 'back');
assert.equal(backReplacement.sourceManifest.regions.find(region => region.id === 'original-chest')?.view, 'front', 'Back replacement retains legacy front source evidence');
const untaggedBack = { ...legacySources, sourceManifest: { ...legacySources.sourceManifest,
  backView: { view: 'back' as const, partIds: ['original-back'] },
  regions: [...legacySources.sourceManifest.regions, { ...front.sourceManifest.regions[0], id: 'original-back', view: undefined }] } };
assert.equal(mergeImportedGarmentView(untaggedBack, untaggedBack, 'back').sourceManifest.regions.find(region => region.id === 'original-back')?.view, 'back', 'Source-view metadata takes precedence over the primary-view fallback');
const actualCollision = { ...fixture('back'), sourceManifest: { ...fixture('back').sourceManifest,
  regions: [{ ...front.sourceManifest.regions[0], id: 'original-chest', view: 'back' as const }] } };
assert.throws(() => mergeImportedGarmentView(legacySources, actualCollision, 'back'), /colliding source-region IDs/, 'Genuine cross-view ID collisions must still fail');
const duplicatedSource = { ...legacySources, sourceManifest: { ...legacySources.sourceManifest, regions: [...legacySources.sourceManifest.regions, legacySources.sourceManifest.regions[0]] } };
assert.throws(() => mergeImportedGarmentView(legacySources, duplicatedSource, 'front'), /colliding source-region IDs/, 'Duplicate IDs within one response must still fail');
assert.deepEqual(importedGarmentLayers(combined, 'back').find(layer => layer.id === 'back-upper')?.fabricRegion, { role: 'body' }, 'Fabric opt-in resolves the requested view');
const crossView = mergeImportedGarmentView(linked, patchConstructionRegion(fixture('back'), 'back', 'back-upper', {
  colourGroupId: linked.constructionRegions!.regions[0].colourGroupId, fabricGroupId: linked.constructionRegions!.regions[0].fabricGroupId,
}), 'back');
assert.deepEqual(recolorImportedParts(crossView, 'front-upper', '#abcdef', 'group'), { 'front-upper': '#abcdef', 'front-lower': '#abcdef' }, 'Matching group strings never copy colour to back');
assert.deepEqual(importedGarmentLayers(crossView, 'back').find(layer => layer.id === 'back-upper')?.fabricRegion, { role: 'body' }, 'Fabric linkage is view-local');
assert.equal(constructionRegionsForView(combined, 'back')?.status, 'needs-review');
assert.equal(constructionNeedsReview(combined), true);
assert.throws(() => linkConstructionRegions(combined, 'front', 'front-upper', 'back-upper'));
const reviewed = reviewConstructionRegions(combined, 'back');
assert.equal(constructionNeedsReview(reviewed), false);
const restored = normalizeImportedGarment(JSON.parse(JSON.stringify(reviewed)));
assert.deepEqual(restored.manifest.frontView?.constructionRegions, reviewed.manifest.frontView?.constructionRegions);
assert.deepEqual(restored.manifest.backView?.constructionRegions, reviewed.manifest.backView?.constructionRegions);
const replaceFront = mergeImportedGarmentView(restored, fixture(), 'front');
assert.equal(replaceFront.manifest.backView?.constructionRegions?.status, 'reviewed');
assert.equal(replaceFront.constructionRegions?.status, 'needs-review');
const rawTrace = fixture(); delete rawTrace.constructionRegions; delete rawTrace.manifest.frontView!.constructionRegions;
const replaceTrace = mergeImportedGarmentView(restored, rawTrace, 'front');
assert.equal(replaceTrace.constructionRegions, undefined, 'Replacing with trace discards stale front regions');
assert.equal(replaceTrace.manifest.backView?.constructionRegions?.status, 'reviewed');
const callbacks = { onSelect() {}, onChange() {} };
const markup = renderToStaticMarkup(createElement(ImportedConstructionRegionReview, { value: withSeam, view: 'front', selectedId: 'front-upper', ...callbacks }));
for (const label of ['Construction region list', 'Pristine traced construction ink', 'Region name', 'Semantic type', 'Builder category', 'Merge regions', 'Evidenced seam', 'Split along selected seam', 'Link symmetrical pair', 'Unlink pair', 'Fabric group', 'Colour group', 'Confirm construction region review']) assert.ok(markup.includes(label), label);
assert.ok(markup.indexOf('data-construction-ink') > markup.indexOf('data-region-id'), 'Pristine ink renders above fills');
const editor = renderToStaticMarkup(createElement(ImportedGarmentEditor, { value: front, view: 'front', step: 2, selectedId: null, ...callbacks, onColor() {}, onReplace() {}, onResetColors() {} }));
assert.match(editor, /Construction regions/);
assert.match(editor, /disabled=""[^>]*>.*?Use reviewed construction regions/s);
assert.ok(editor.includes('Generate estimated back'), 'Explicit back inference should remain available without redrawing the clean front');
console.log('PASS construction region persistence, confidence review gate, immutable ink, corrections, pairs, seam candidates and SSR controls');
