import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const base=process.env.CERIGA_BASE_URL||'http://127.0.0.1:5189';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.setDefaultTimeout(30000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${base}/builder/hd-001`);
  await page.getByRole('button',{name:'Continue',exact:true}).waitFor();
  for(let i=0;i<10&&!await page.getByRole('button',{name:'Continue to Review',exact:true}).isVisible();i++)await page.getByRole('button',{name:'Continue',exact:true}).first().click();
  const zone=page.locator('[data-print-design-zone]');
  const assets=()=>page.getByRole('button',{name:'Assets',exact:true}).click();
  await assets();await page.getByRole('button',{name:'+ Create Asset',exact:true}).click();
  await page.getByRole('textbox',{name:'Asset name',exact:true}).fill('Editable typography');
  await page.getByRole('button',{name:'Typography',exact:true}).click();
  await page.getByRole('textbox',{name:'Type, then add',exact:true}).fill('CERIGA');
  await page.getByRole('button',{name:'Add',exact:true}).click();
  const panel=page.locator('[data-text-effects-panel]');
  await panel.locator('summary').click();
  assert.equal(await panel.getByRole('button',{name:/^Add .* effect$/}).count(),34);
  assert.equal(await panel.locator('canvas').count(),34);
  const add=name=>panel.getByRole('button',{name:`Add ${name} effect`,exact:true}).click();
  const ready=async()=>{try{await page.waitForFunction(()=>!document.querySelector('[data-print-design-zone] [data-text-effects-pending="true"]'),{},{timeout:30000});}catch(error){console.error(await zone.locator('[data-text-effects]').evaluateAll(nodes=>nodes.map(node=>({error:node.getAttribute('data-text-effects-error'),html:node.outerHTML.slice(0,1800)}))));throw error;}};
  const pixels=()=>zone.locator('[data-text-effects-canvas]').first().evaluate(canvas=>canvas.toDataURL());
  await add('Chrome');await ready();
  const full=await pixels();
  await panel.getByLabel('Effect intensity',{exact:true}).fill('35');await ready();
  assert.notEqual(await pixels(),full,'Live input changes rendered effect');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  assert.equal(await panel.getByLabel('Effect intensity',{exact:true}).inputValue(),'100');
  await page.getByRole('button',{name:'Redo',exact:true}).click();
  assert.equal(await panel.getByLabel('Effect intensity',{exact:true}).inputValue(),'35');
  await add('Distressed');await ready();
  const worn=await pixels();
  await panel.getByRole('button',{name:'Randomise',exact:true}).click();await ready();
  assert.notEqual(await pixels(),worn);
  await add('3D / Extrude');
  await panel.getByLabel('Effect Depth',{exact:true}).fill('24');await ready();
  const stacked=await pixels();
  await panel.getByRole('button',{name:'Move 3D / Extrude effect 3 up',exact:true}).click();await ready();
  assert.notEqual(await pixels(),stacked);
  await panel.getByRole('button',{name:'Hide Chrome effect 1',exact:true}).click();
  assert.equal(await panel.getByRole('button',{name:'Show Chrome effect 1',exact:true}).count(),1);
  await panel.getByRole('button',{name:'Show Chrome effect 1',exact:true}).click();
  await panel.getByRole('button',{name:'Duplicate Chrome effect 1',exact:true}).click();
  assert.equal(await panel.getByRole('button',{name:/^Edit .* effect \d+$/}).count(),4);
  await panel.getByRole('button',{name:'Remove Chrome effect 2',exact:true}).click();
  await add('Gradient');
  await panel.getByLabel('Effect Gradient Type',{exact:true}).selectOption('conic');
  await panel.getByRole('button',{name:'Add stop',exact:true}).click();
  assert.equal(await panel.getByLabel('Stop 3 colour',{exact:true}).count(),1);
  await panel.getByLabel('Stop 3 colour',{exact:true}).fill('#44ee66');
  await panel.getByLabel('Stop 3 position',{exact:true}).fill('65');
  await panel.getByRole('button',{name:'Remove Gradient effect 4',exact:true}).click();
  await add('Image Fill');
  const svg=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><path fill="#e30" d="M0 0h32v64H0z"/><path fill="#38f" d="M32 0h32v64H32z"/></svg>');
  await panel.getByLabel('Upload fill image',{exact:true}).setInputFiles({name:'fill.svg',mimeType:'image/svg+xml',buffer:svg});
  await panel.locator('img[alt="Current fill source"]').waitFor();await ready();
  const imageFilled=await pixels();
  await panel.getByLabel('Effect Rotation',{exact:true}).fill('40');
  await panel.getByLabel('Effect Crop Width',{exact:true}).fill('70');await ready();
  assert.notEqual(await pixels(),imageFilled,'Image fill transformation remains editable');
  await panel.getByRole('button',{name:'Remove Image Fill effect 4',exact:true}).click();
  await ready();
  const layer=zone.locator('[data-print-id]').first();
  await layer.locator('[data-text-effects]').dblclick();
  const editor=layer.locator('textarea');await editor.fill('COLLECTION 01');await editor.press('Tab');
  await ready();
  assert.equal(await layer.locator('[data-text-effects-canvas]').getAttribute('aria-label'),'COLLECTION 01');
  await page.getByRole('slider',{name:'Curve amount',exact:true}).fill('65');await ready();
  assert((await layer.locator('textPath').count())>0,'Curved source remains live and editable');
  await page.getByRole('button',{name:'Save Asset',exact:true}).click();
  await page.locator('[data-asset-artboard]').waitFor({state:'detached'});
  await assets();await page.getByRole('button',{name:'Edit Asset',exact:true}).click();
  await zone.locator('[data-print-id]').first().click();
  await page.getByRole('button',{name:'Typography',exact:true}).click();
  await panel.locator('summary').click();
  assert.equal(await panel.getByRole('button',{name:/^Edit .* effect \d+$/}).count(),3,'Saved source keeps effects stack');
  await ready();
  assert.equal(await zone.locator('[data-text-effects-canvas]').getAttribute('aria-label'),'COLLECTION 01');
  await page.getByRole('button',{name:'← Back to Garment',exact:true}).click();
  await page.getByRole('button',{name:'Typography',exact:true}).click();
  await page.getByRole('textbox',{name:'Type, then add',exact:true}).fill('FRONT');
  await page.getByRole('button',{name:'Add',exact:true}).click();
  await panel.locator('summary').click();await add('Chrome');await ready();
  await page.getByRole('button',{name:'Duplicate',exact:true}).first().click();await ready();
  assert.equal(await zone.locator('[data-text-effects-canvas]').count(),2,'Duplicate retains editable effects');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await page.getByRole('button',{name:/^back$/i}).last().click();
  await page.getByRole('button',{name:'Typography',exact:true}).click();
  await page.getByRole('textbox',{name:'Type, then add',exact:true}).fill('BACK');
  await page.getByRole('button',{name:'Add',exact:true}).click();
  await panel.locator('summary').click();await add('Neon');await ready();
  await page.getByRole('button',{name:'Continue to Review',exact:true}).click();
  for(let i=0;i<2;i++)await page.getByRole('button',{name:'Continue',exact:true}).first().click();
  await page.getByRole('button',{name:/Reset size split|One per size/}).first().click();
  await page.getByRole('button',{name:'Continue',exact:true}).first().click();
  await page.getByRole('button',{name:'Order',exact:true}).waitFor();
  await page.getByRole('button',{name:'Order',exact:true}).click();await page.waitForURL('**/delivery');
  await page.reload();
  await page.locator('[data-project-garment-side="front"] [data-text-effects-canvas][aria-label="FRONT"]').first().waitFor();
  await page.locator('[data-project-garment-side="back"] [data-text-effects-canvas][aria-label="BACK"]').first().waitFor();
  await page.waitForFunction(()=>!document.querySelector('[data-project-garment-side] [data-text-effects-pending="true"]'));
  assert.equal(await page.locator('[data-text-effects-error]').count(),0);
  assert.deepEqual(errors,[]);
  console.log('Text effects editor: visual gallery, live controls, stack actions, history, image/gradient fill, editable source, Asset Builder and front/back persistence passed. No order submitted.');
}finally{await browser.close();}
