import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { createRequire } from 'node:module';
const result = await build({ stdin: { contents: `export * from './src/app/lib/patternEditing'; export * from './src/app/components/builder/printsStudio/studioAssets';`, resolveDir: process.cwd() }, bundle: true, write: false, platform: 'node', format: 'cjs' });
const module = { exports: {} };
new Function('module', 'exports', 'require', result.outputFiles[0].text)(module, module.exports, createRequire(import.meta.url));
const { patternAppearance, encodeStudioDrag, decodeStudioDrag, initialPatternSettings, changePatternType, customPatternSettings } = module.exports;
const source = 'data:image/svg+xml;base64,PHN2Zy8+';
const custom = { ...initialPatternSettings('custom'), ...customPatternSettings({ src: source, name: 'Logo', width: 200, height: 100 }), patternRepeat: 'random', patternCount: 12, patternSpacingX: 20, patternSpacingY: 4, patternRandomPosition: 65, patternRandomRotation: 80, patternMinScale: 70, patternMaxScale: 130, opacity: 53, flipHorizontal: true };
const roundtrip = decodeStudioDrag(encodeStudioDrag('pattern', 'custom', custom));
assert.deepEqual(roundtrip.settings, patternAppearance(custom));
assert.equal(roundtrip.settings.patternSource, source);
assert.equal(roundtrip.settings.flipHorizontal, true);
assert.equal(decodeStudioDrag('null'), null);
assert.equal(decodeStudioDrag('{"kind":"pattern","id":"missing"}'), null);
assert.deepEqual(decodeStudioDrag(encodeStudioDrag('shape', 'rect')), { kind: 'shape', id: 'rect' });
assert.deepEqual(decodeStudioDrag('{"kind":"pattern","id":"dots"}'), { kind: 'pattern', id: 'dots' });
const safe = patternAppearance({ id: 'overwrite', type: 'text', patternTarget: 'wrong', x: 999, children: [], rotation: 17, locked: true, opacity: -1, patternSource: 'javascript:alert(1)', patternCount: 999, patternSeed: Infinity, patternRepeat: 'bad', patternMinScale: -50, patternColors: ['#abcdef', '<svg>'] });
assert.deepEqual(safe, { opacity: 0, patternCount: 32, patternMinScale: 10, patternColors: ['#abcdef'] });
const area = { id: 'area', type: 'customArea', customAreaPattern: 'custom', patternSource: source, color: '#ffeecc', width: 100, height: 80, x: 50, y: 60, customAreaPoints: [{ x: 0, y: 0 }, { x: 50, y: 80 }, { x: 100, y: 0 }], patternSeed: 123, patternScale: 180, patternCount: 7 };
const camo = { ...area, ...changePatternType(area, 'camo') };
assert.equal(camo.customAreaPattern, 'camo'); assert.equal(camo.patternColors.length, 4);
assert.equal(camo.patternSource, source); assert.equal(camo.patternScale, 180); assert.equal(camo.patternCount, 7); assert.equal(camo.patternSeed, 123);
assert.equal(camo.customAreaPoints, area.customAreaPoints);
const back = { ...camo, ...changePatternType(camo, 'custom') }; assert.equal(back.patternSource, source);
const reset = { ...custom, ...initialPatternSettings('dots') };
assert.equal(reset.patternSource, undefined); assert.equal(reset.patternRepeat, 'grid'); assert.equal(reset.patternSpacingX, 0); assert.equal(reset.flipHorizontal, false);
console.log('PASS: appearance-only drag payload, validation, legacy compatibility, custom source persistence, palette/type changes, immutable clipping geometry and drop defaults.');
