import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import sharp from 'sharp';

const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(15000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${process.env.CERIGA_BASE_URL || 'http://127.0.0.1:5189'}/builder/hd-001`);
  await page.getByRole('button', { name: 'Continue', exact: true }).waitFor();
  for (let step = 0; step < 10 && !await page.getByRole('button', { name: 'Continue to Review', exact: true }).isVisible(); step++) await page.getByRole('button', { name: 'Continue', exact: true }).first().click();
  await page.getByRole('button', { name: 'Continue to Review', exact: true }).waitFor();
  const zone = page.locator('[data-print-design-zone]');
  const drop = async (id, kind = 'shape', fraction = .5) => zone.evaluate((node, args) => {
    const box = node.getBoundingClientRect(); const dataTransfer = new DataTransfer();
    dataTransfer.setData('application/x-ceriga-asset', JSON.stringify({ kind: args.kind, id: args.id }));
    node.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer, clientX: box.x + box.width * args.fraction, clientY: box.y + box.height * .5 }));
  }, { id, kind, fraction });
  const assets = async () => { await page.getByRole('button', { name: /^Assets/ }).first().click(); };
  await drop('rect');
  const frontId = await zone.locator('[data-print-id]').getAttribute('data-print-id');
  await page.getByRole('button', { name: /^back$/i }).last().click();
  await drop('triangle');
  const backId = await zone.locator('[data-print-id]').getAttribute('data-print-id');
  await assets();
  await page.getByRole('button', { name: '+ Create Asset', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor();
  assert.equal(await zone.locator('[data-print-id]').count(), 0);
  assert.equal(await page.getByRole('button', { name: /^front$/i }).count(), 0);
  assert.equal(await page.getByRole('button', { name: /^back$/i }).count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Continue to Review', exact: true }).count(), 0);
  await page.getByLabel('Asset size preset').selectOption('landscape');
  assert.equal(await page.getByLabel('Asset width', { exact: true }).inputValue(), '900');
  await drop('rect', 'shape', .02);
  await drop('ellipse');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await zone.locator('[data-print-id]').count(), 1);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  assert.equal(await zone.locator('[data-print-id]').count(), 2);
  await page.getByRole('checkbox', { name: 'Select layer 1 for group or merge', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Select layer 2 for group or merge', exact: true }).check();
  await page.getByRole('button', { name: /^Group/ }).filter({ hasText: 'Group' }).last().click();
  assert.equal(await zone.locator(':scope > [data-print-id]').count(), 1);
  await page.getByLabel('Layer name', { exact: true }).fill('Editable shape group');
  await page.getByRole('button', { name: 'Hide group layer', exact: true }).click();
  assert.equal(await zone.locator(':scope > [data-print-id]').count(), 0);
  await page.getByRole('button', { name: 'Show group layer', exact: true }).click();
  await page.getByRole('button', { name: 'Duplicate', exact: true }).first().click();
  assert.equal(await zone.locator(':scope > [data-print-id]').count(), 2);
  const childIds = await zone.locator('[data-group-child]').evaluateAll(nodes => nodes.map(node => node.dataset.groupChild));
  assert.equal(new Set(childIds).size, 4, 'Duplicated groups have unique child rendering IDs');
  await page.getByRole('button', { name: 'Delete layer', exact: true }).first().click();
  assert.equal(await zone.locator(':scope > [data-print-id]').count(), 1);
  await page.getByRole('button', { name: 'Save Asset', exact: true }).click();
  await page.getByRole('dialog', { name: 'Asset Name', exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Save asset name', exact: true }).fill('Test graphic');
  await page.getByRole('dialog').getByRole('button', { name: 'Save Asset', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor({ state: 'detached', timeout: 30000 });
  assert.equal(await zone.locator(`[data-print-id="${backId}"]`).count(), 1);
  const placed = zone.locator('[data-print-id^="asset-"]');
  await placed.waitFor();
  assert.equal(await placed.locator('[data-handles]').count() > 0, true);
  const png = await placed.locator('img').getAttribute('src');
  const { data, info } = await sharp(Buffer.from(png.split(',')[1], 'base64')).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  assert.equal(info.width, 900); assert.equal(info.height, 600);
  assert.equal(data[3], 0, 'Canvas background remains transparent');
  assert(data.some((v, i) => i % 4 === 3 && v > 0), 'Export contains artwork');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await zone.locator('[data-print-id^="asset-"]').count(), 0);
  assert.equal(await zone.locator(`[data-print-id="${backId}"]`).count(), 1);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await page.getByRole('button', { name: /^front$/i }).last().click();
  assert.equal(await zone.locator(`[data-print-id="${frontId}"]`).count(), 1);
  await assets();
  await page.getByRole('button', { name: 'Edit Asset', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor();
  assert.equal(await zone.locator('[data-group-child]').count(), 2);
  await page.getByRole('textbox', { name: 'Asset name', exact: true }).fill('Changed graphic');
  await page.getByRole('button', { name: '← Back to Garment', exact: true }).click();
  await page.getByRole('button', { name: 'Continue Editing', exact: true }).click();
  await page.getByRole('button', { name: 'Save as New Asset', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor({ state: 'detached', timeout: 30000 });
  assert.equal(await zone.locator(`[data-print-id="${frontId}"]`).count(), 1);
  await assets();
  assert.equal(await page.getByRole('button', { name: 'Edit Asset', exact: true }).count(), 2);
  await page.getByRole('button', { name: '+ Create Asset', exact: true }).click();
  await drop('dots', 'pattern');
  await page.getByRole('button', { name: '← Back to Garment', exact: true }).click();
  await page.getByRole('button', { name: 'Discard Changes', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor({ state: 'detached' });
  await assets();
  await page.getByRole('button', { name: 'Place Test graphic', exact: true }).click();
  assert.equal(await zone.locator('[data-print-id^="asset-"]').count(), 2);
  await page.getByRole('button', { name: 'Place Test graphic', exact: true }).evaluate(button => {
    const dataTransfer = new DataTransfer();
    button.dispatchEvent(new DragEvent('dragstart', { bubbles: true, dataTransfer }));
    const target = document.querySelector('[data-print-design-zone]');
    const box = target.getBoundingClientRect();
    target.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer, clientX: box.x + box.width * .4, clientY: box.y + box.height * .5 }));
  });
  assert.equal(await zone.locator('[data-print-id^="asset-"]').count(), 3);
  await page.getByRole('button', { name: '+ Create Asset', exact: true }).click();
  await page.getByLabel('Asset size preset').selectOption('custom');
  await page.getByLabel('Asset width', { exact: true }).fill('720');
  await page.getByLabel('Asset height', { exact: true }).fill('480');
  await page.getByLabel('Asset height', { exact: true }).press('Enter');
  await page.getByRole('textbox', { name: 'Asset name', exact: true }).fill('Brush graphic');
  await page.getByRole('button', { name: /^Drawing/ }).first().click();
  await page.getByRole('button', { name: 'Brush', exact: true }).first().click();
  await page.getByLabel('Brush preset', { exact: true }).selectOption('pen');
  const drawCanvas = page.locator('[data-print-draw-layer]');
  const box = await drawCanvas.boundingBox();
  await page.mouse.move(box.x + box.width * .4, box.y + box.height * .45);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * .6, box.y + box.height * .55, { steps: 20 });
  await page.mouse.up();
  await zone.locator(':scope > [data-print-id]').waitFor();
  await zone.locator(':scope > [data-print-id]').evaluate(node => { const image = document.createElement('img'); image.dataset.testBrokenImage = ''; image.src = 'data:image/png;base64,broken'; node.append(image); });
  await page.getByRole('button', { name: 'Save Asset', exact: true }).click();
  await page.locator('header [role="alert"]').waitFor();
  assert.equal(await page.locator('[data-asset-artboard]').count(), 1, 'Failed save keeps editable document');
  await page.locator('[data-test-broken-image]').evaluate(node => node.remove());
  await page.getByRole('button', { name: 'Save Asset', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor({ state: 'detached', timeout: 30000 });
  const drawingPng = await zone.locator('[data-print-id^="asset-"]').last().locator('img').getAttribute('src');
  const drawingExport = await sharp(Buffer.from(drawingPng.split(',')[1], 'base64')).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  assert.equal(drawingExport.info.width, 720); assert.equal(drawingExport.info.height, 480);
  assert(drawingExport.data.some((value, index) => index % 4 === 3 && value > 0), 'Saving while brush active includes drawing');
  await assets();
  await page.getByRole('button', { name: '+ Create Asset', exact: true }).click();
  await drop('rect');
  await page.waitForFunction(async () => (await (await import('/src/app/lib/assetLibraryStorage.ts')).readStoredAssets('asset-draft:guest')).length === 1);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await page.waitForFunction(async () => (await (await import('/src/app/lib/assetLibraryStorage.ts')).readStoredAssets('asset-draft:guest')).length === 0);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await page.waitForFunction(async () => (await (await import('/src/app/lib/assetLibraryStorage.ts')).readStoredAssets('asset-draft:guest')).length === 1);
  await page.reload();
  for (let step = 0; step < 10 && !await page.getByRole('button', { name: 'Continue to Review', exact: true }).isVisible(); step++) await page.getByRole('button', { name: 'Continue', exact: true }).first().click();
  await assets();
  assert.equal(await page.getByRole('button', { name: 'Edit Asset', exact: true }).count(), 3, 'Saved library survives reload');
  await page.getByRole('button', { name: 'Resume asset draft', exact: true }).click();
  assert.equal(await zone.locator(':scope > [data-print-id]').count(), 1, 'Unfinished source survives reload');
  await page.getByRole('button', { name: '← Back to Garment', exact: true }).click();
  await page.getByRole('button', { name: 'Discard Changes', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor({ state: 'detached' });
  await assets();
  await page.getByRole('button', { name: 'Edit Asset', exact: true }).first().click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-asset-artboard]').waitFor({ state: 'visible' });
  assert.equal(await page.getByRole('button', { name: 'Save Changes', exact: true }).isVisible(), true);
  assert.equal(await page.getByRole('button', { name: '← Back to Garment', exact: true }).isVisible(), true);
  assert.equal(await page.getByRole('button', { name: /^front$/i }).count(), 0);
  await page.getByRole('button', { name: '← Back to Garment', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor({ state: 'detached' });
  assert.deepEqual(errors, []);
  console.log('Asset workspace passed: isolated documents/history, dimensions, groups, transparent save, source editing, drag/drop, drawing, failed-save recovery, durable library/drafts and mobile mode.');
} finally { await browser.close(); }
