import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${process.env.CERIGA_BASE_URL || 'http://127.0.0.1:5189'}/builder/hd-001`);
  await page.getByRole('button', { name: 'Continue', exact: true }).waitFor();
  for (let i = 0; i < 10 && !await page.getByRole('button', { name: 'Continue to Review', exact: true }).isVisible(); i++) await page.getByRole('button', { name: 'Continue', exact: true }).first().click();
  await page.getByRole('button', { name: 'Brush', exact: true }).first().click();
  const preset = page.getByLabel('Brush preset', { exact: true });
  const texture = page.getByLabel('Texture', { exact: true });
  assert.equal(await preset.locator('option').count(), 41);
  assert.equal(await texture.locator('option').count(), 47);
  const setRange = (name, value) => page.getByRole('slider', { name, exact: true }).evaluate((input, value) => {
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, String(value));
    input.dispatchEvent(new Event('input', { bubbles: true }));
    input.dispatchEvent(new Event('change', { bubbles: true }));
  }, value);
  const preview = page.getByLabel('Live brush preview', { exact: true });
  const snapshot = () => preview.evaluate(canvas => canvas.toDataURL());
  await texture.selectOption('canvas');
  await setRange('Texture scale', 170);
  await preset.selectOption('dry-brush');
  assert.equal(await texture.inputValue(), 'canvas', 'Preset selection must preserve independent texture');
  assert.equal(await page.getByRole('slider', { name: 'Texture scale', exact: true }).inputValue(), '170');
  let before = await snapshot();
  await setRange('Texture rotation', 43);
  await page.waitForFunction(before => document.querySelector('canvas[aria-label="Live brush preview"]').toDataURL() !== before, before);
  before = await snapshot();
  await setRange('Spacing', 200);
  await page.waitForFunction(before => document.querySelector('canvas[aria-label="Live brush preview"]').toDataURL() !== before, before);
  await texture.selectOption('custom');
  const custom = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 32; canvas.height = 32;
    const ctx = canvas.getContext('2d'); ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 32, 32);
    ctx.fillStyle = 'black'; ctx.fillRect(0, 0, 10, 32); return canvas.toDataURL().split(',')[1];
  });
  await page.getByLabel('Upload texture image', { exact: true }).setInputFiles({ name: 'grain.png', mimeType: 'image/png', buffer: Buffer.from(custom, 'base64') });
  await page.getByText('Custom mask ready.', { exact: false }).waitFor();
  before = await snapshot();
  await page.getByRole('switch', { name: 'Invert texture', exact: true }).click();
  await page.waitForFunction(before => document.querySelector('canvas[aria-label="Live brush preview"]').toDataURL() !== before, before);
  await preset.selectOption('drip-paint');
  before = await snapshot();
  await page.getByRole('button', { name: 'Randomise brush', exact: true }).click();
  await page.waitForFunction(before => document.querySelector('canvas[aria-label="Live brush preview"]').toDataURL() !== before, before);
  await texture.selectOption('smooth');
  await preset.selectOption('pen');
  for (const [name, value] of [['Brush size', 64], ['Grain', 0], ['Stabilisation Strength', 0], ['Stroke smoothing', 0]]) await setRange(name, value);
  const draw = page.locator('[data-print-draw-layer]');
  const drawStroke = async () => {
    const box = await draw.boundingBox();
    await page.mouse.move(box.x + box.width * .43, box.y + box.height * .44);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * .57, box.y + box.height * .44, { steps: 12 });
    await page.mouse.up();
  };
  await drawStroke();
  const image = page.locator('[data-print-id] img').first();
  await image.waitFor();
  const original = await image.getAttribute('src');
  const count = await page.locator('[data-print-id]').count();
  await preset.selectOption('distress-brush');
  assert.equal(await page.getByLabel('Distress mode', { exact: true }).inputValue(), 'erase');
  await setRange('Brush size', 42);
  await setRange('Stabilisation Strength', 0);
  await setRange('Stroke smoothing', 0);
  await drawStroke();
  await page.waitForFunction(original => document.querySelector('[data-print-id] img')?.getAttribute('src') !== original, original);
  assert.equal(await page.locator('[data-print-id]').count(), count, 'Remove must not add a paint layer');
  const removed = await image.getAttribute('src');
  const alpha = async source => page.evaluate(async source => {
    const img = new Image(); img.src = source; await img.decode();
    const canvas = document.createElement('canvas'); canvas.width = img.width; canvas.height = img.height;
    const ctx = canvas.getContext('2d'); ctx.drawImage(img, 0, 0);
    return ctx.getImageData(0, 0, canvas.width, canvas.height).data.reduce((total, v, i) => total + (i % 4 === 3 ? v : 0), 0);
  }, source);
  assert(await alpha(removed) < await alpha(original), 'Distress must remove actual ink');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await image.getAttribute('src'), original);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  assert.equal(await image.getAttribute('src'), removed);
  await page.getByLabel('Distress mode', { exact: true }).selectOption('paint');
  await drawStroke();
  assert.equal(await page.locator('[data-print-id]').count(), count + 1, 'Paint mode creates worn ink');
  await page.setViewportSize({ width: 390, height: 844 });
  await texture.scrollIntoViewIfNeeded();
  assert(await texture.isVisible());
  assert.equal(errors.length, 0, errors.join('\n'));
  console.log('Brush editor: 41 presets, 47 textures, live preview, custom mask, independent settings, distress paint/remove and Undo/Redo passed.');
} finally { await browser.close(); }
