import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { chromium } from 'playwright';
const baseUrl = process.env.CERIGA_BASE_URL || 'http://127.0.0.1:5189';
const bundle = await build({ stdin: { loader:'tsx', resolveDir:process.cwd(), contents:`
  import React,{useState} from 'react';
  import {createRoot} from 'react-dom/client';
  import {PrintsDesignStep,PrintsDesignPreview} from './src/app/components/builder/PrintsDesignStep';
  import {PrintsStudioProvider,usePrintsStudio} from './src/app/components/builder/printsStudio/PrintsStudioContext';
  import {shapeToEditablePath} from './src/app/lib/shapeGeometry';
  import {createTextEffect} from './src/app/lib/textEffects';
  function Fixture(){
    const studio=usePrintsStudio();
    const [elements,change]=useState([{id:'shape',type:'shape',content:'star',x:300,y:280,width:220,height:220,rotation:0,color:'#ec5454',shapeFilled:true,borderWidth:4}]);
    const [selected,select]=useState('shape');
    window.shapeState={elements,selected,pathEditingId:studio.pathEditingId};
    window.patchShape=patch=>change(items=>items.map(item=>item.id===selected?{...item,...patch}:item));
    window.polygonTool=()=>{select(null);studio.setTool('shapePolygon');};
    window.shapeEffects=()=>change(items=>items.map(item=>({...item,shapeEffects:[createTextEffect('glow'),createTextEffect('distressed')]})));
    return <><aside style={{width:330,height:750,overflow:'auto'}}><PrintsDesignStep elements={elements} onChange={change} selectedLayerId={selected} onSelectedLayerIdChange={select}/></aside><main style={{position:'absolute',left:350,top:50,width:650,height:640}}><PrintsDesignPreview assetMode editable garmentPreview={null} canvasSize={{width:650,height:640}} className="h-full w-full" elements={elements} onChange={change} selectedLayerId={selected} onSelectedLayerIdChange={select}/></main></>;
  }
  createRoot(document.getElementById('root')).render(<PrintsStudioProvider><Fixture/></PrintsStudioProvider>);
` }, bundle:true, write:false, format:'iife', platform:'browser', jsx:'automatic', define:{'process.env.NODE_ENV':'"production"','import.meta.url':JSON.stringify(`${baseUrl}/src/app/lib/textEffectRendering.ts`)},loader:{'.svg':'dataurl','.png':'dataurl','.jpg':'dataurl'},logLevel:'silent'});
const browser = await chromium.launch({channel:'msedge',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1250,height:900}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/__shape-editor',route=>route.fulfill({contentType:'text/html',body:'<link rel="stylesheet" href="/src/styles/index.css?direct"><div id="root"></div>'}));
  await page.goto(baseUrl+'/__shape-editor');await page.addScriptTag({content:bundle.outputFiles[0].text});
  await page.getByRole('button',{name:'Convert to Editable Path',exact:true}).click();
  await page.locator('[data-shape-path-editor]').waitFor();
  assert.equal(await page.locator('[data-print-id="shape"] [data-handles]').count(),0,'Path mode hides ordinary transform handles');
  assert.equal(await page.locator('[data-shape-anchor]').count(),10);
  const getNode= index=>page.evaluate(index=>window.shapeState.elements[0].shapePath.nodes[index],index);
  const anchor=page.locator('[data-shape-anchor="0"]');
  const first=await getNode(0), second=await getNode(1);
  const click=async locator=>{const b=await locator.boundingBox();assert(b);await page.mouse.click(b.x+b.width/2,b.y+b.height/2);};
  await click(anchor);
  await page.keyboard.down('Shift');await click(page.locator('[data-shape-anchor="1"]'));await page.keyboard.up('Shift');
  const start=await anchor.boundingBox();await page.mouse.move(start.x+start.width/2,start.y+start.height/2);await page.mouse.down();await page.mouse.move(start.x+start.width/2+22,start.y+start.height/2+11,{steps:4});await page.mouse.up();
  const moved=await getNode(0),movedSecond=await getNode(1);
  assert(Math.abs(moved.x-first.x-10)<1);assert(Math.abs(movedSecond.x-second.x-10)<1,'Multi-point movement');
  await page.getByRole('button',{name:'Curve points',exact:true}).click();
  assert((await getNode(0)).in);assert((await getNode(1)).out);
  const handle=page.locator('[data-shape-curve-handle="out"]').first();const hb=await handle.boundingBox();const before=await getNode(0);
  await page.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2);await page.mouse.down();await page.mouse.move(hb.x+hb.width/2+10,hb.y+hb.height/2+12);await page.mouse.up();
  assert.notDeepEqual((await getNode(0)).out,before.out);
  await page.keyboard.press('Delete');
  assert.equal(await page.locator('[data-shape-anchor]').count(),8);assert.equal(await page.locator('[data-print-id="shape"]').count(),1,'Delete points, not layer');
  const segment=page.locator('[data-shape-path-editor] svg > path').nth(2);
  const segmentPoint=await segment.evaluate(path=>{const p=path.getPointAtLength(path.getTotalLength()/2).matrixTransform(path.getScreenCTM());return{x:p.x,y:p.y};});
  await page.mouse.dblclick(segmentPoint.x,segmentPoint.y);
  assert.equal(await page.locator('[data-shape-anchor]').count(),9,'Double click adds anchor');
  await page.keyboard.press('Escape');assert.equal(await page.locator('[data-shape-path-editor]').count(),0);
  assert.equal(await page.locator('[data-print-id="shape"] [data-handles]').count(),1);
  await page.evaluate(()=>window.patchShape({rotation:30,flipHorizontal:true,perspective:[{x:.1,y:.1},{x:.9,y:0},{x:1,y:.9},{x:0,y:1}]}));
  await page.getByRole('button',{name:'Edit Path',exact:true}).click();
  const rotated=page.locator('[data-shape-anchor="2"]');const rb=await rotated.boundingBox();const old=await getNode(2);
  await page.mouse.move(rb.x+rb.width/2,rb.y+rb.height/2);await page.mouse.down();await page.mouse.move(rb.x+rb.width/2+15,rb.y+rb.height/2+10);await page.mouse.up();assert.notDeepEqual(await getNode(2),old);
  await page.keyboard.press('Escape');
  await page.evaluate(()=>window.polygonTool());
  const draft=page.locator('[data-shape-polygon-draft] svg');await draft.waitFor();const box=await draft.boundingBox();
  await page.mouse.click(box.x+100,box.y+100);await page.mouse.click(box.x+260,box.y+110);await page.mouse.click(box.x+240,box.y+260);await page.mouse.click(box.x+100,box.y+100);
  assert.equal(await page.locator('[data-shape-polygon-draft]').count(),0);
  const created=await page.evaluate(()=>window.shapeState.elements[1]);assert.equal(created.content,'custom-polygon');assert.equal(created.shapePath.nodes.length,3);assert(created.shapePath.closed);
  await page.getByRole('button',{name:'Edit Path',exact:true}).click();assert.equal(await page.locator('[data-shape-anchor]').count(),3);await page.keyboard.press('Escape');
  await page.evaluate(()=>window.shapeEffects());
  await page.waitForFunction(()=>document.querySelectorAll('[data-shape-effects-canvas], [data-text-effects-canvas]').length>=2);
  await page.waitForFunction(()=>![...document.querySelectorAll('[data-text-effects-pending]')].some(node=>node.dataset.textEffectsPending==='true'),null,{timeout:60000});
  const state=await page.evaluate(()=>window.shapeState);assert.equal(state.elements[0].type,'shape');assert(state.elements[0].shapePath);assert.equal(state.elements[0].shapeEffects.length,2);
  const effectsPanel = page.locator('[data-shape-effects-panel]');
  await effectsPanel.locator('summary').click();
  await effectsPanel.getByRole('button', {name:'Original / No effects', exact:true}).click();
  await page.evaluate(()=>window.patchShape({shapeFilled:false}));
  await effectsPanel.getByRole('button', {name:'Add Image Fill effect', exact:true}).click();
  assert.equal(await page.evaluate(()=>window.shapeState.elements[1].shapeFilled),true,'Choosing a closed-shape fill enables its interior');
  const imageData = await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=16;const ctx=c.getContext('2d');ctx.fillStyle='#12ce65';ctx.fillRect(0,0,16,16);return c.toDataURL().split(',')[1];});
  await effectsPanel.getByLabel('Upload fill image',{exact:true}).setInputFiles({name:'shape-fill.png',mimeType:'image/png',buffer:Buffer.from(imageData,'base64')});
  await page.waitForFunction(()=>window.shapeState.elements[1].shapeEffects[0].source?.startsWith('data:image/png'));
  await effectsPanel.getByRole('slider',{name:'Effect Opacity',exact:true}).fill('100');
  await page.waitForFunction(()=>!document.querySelector('[data-text-effects-pending="true"]'),null,{timeout:60000});
  const activeCanvas=page.locator(`[data-print-id="${created.id}"] [data-text-effects-canvas]`);
  assert(await activeCanvas.evaluate(canvas=>{const d=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;return d.some((v,i)=>i%4===0&&v===18&&d[i+1]===206&&d[i+2]===101&&d[i+3]===255);}), 'Uploaded image fills the polygon');
  await effectsPanel.getByRole('button',{name:'Duplicate Image Fill effect 1',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.shapeState.elements[1].shapeEffects.length),2);
  await effectsPanel.getByRole('button',{name:'Hide Image Fill effect 2',exact:true}).click();
  await effectsPanel.getByRole('button',{name:'Move Image Fill effect 2 up',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.shapeState.elements[1].shapeEffects[0].enabled),false);
  await effectsPanel.getByRole('button',{name:'Remove Image Fill effect 1',exact:true}).click();
  await page.evaluate(()=>{const p=window.shapeState.elements[1].shapePath;window.patchShape({shapePath:{...p,nodes:p.nodes.map((n,i)=>i===0?{...n,x:-80}:n)}});});
  await page.waitForFunction(()=>!document.querySelector('[data-text-effects-pending="true"]'),null,{timeout:60000});
  assert(await activeCanvas.evaluate(canvas=>parseFloat(canvas.style.left)<-100),'Effects capture includes paths outside the original box');
  await effectsPanel.getByRole('button',{name:'Original / No effects',exact:true}).click();
  await page.evaluate(()=>window.patchShape({content:'line',shapePath:undefined,shapeParameters:undefined}));
  assert.equal(await effectsPanel.getByRole('button',{name:'Add Image Fill effect',exact:true}).count(),0,'Open paths do not expose masked image fills');
  assert.deepEqual(errors,[]);console.log('Shape editor passed: paths, transformed anchors, polygon creation, image fills, stack operations, overflow capture and open-path compatibility.');
}finally{await browser.close();}
