import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(30000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${process.env.CERIGA_BASE_URL || 'http://127.0.0.1:5189'}/builder/hd-001`);
  await page.getByRole('button', { name: 'Continue', exact: true }).waitFor();
  for (let n = 0; n < 10 && !await page.getByRole('button', { name: 'Continue to Review', exact: true }).isVisible(); n++) await page.getByRole('button', { name: 'Continue', exact: true }).first().click();
  const zone = page.locator('[data-print-design-zone]');
  const patterns = () => page.getByRole('button', { name: 'Patterns', exact: true }).click();
  const library = page.locator('[data-pattern-library]');
  const controls = page.locator('[data-pattern-controls]');
  const svg = () => zone.locator('svg[data-pattern]').last();
  const markup = () => svg().evaluate(node => node.innerHTML);
  const slider = (name, value) => controls.getByRole('slider', { name, exact: true }).fill(String(value));
  await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await page.getByRole('button', { name: '+ Create Asset', exact: true }).click();
  await page.getByRole('textbox', { name: 'Asset name', exact: true }).fill('Pattern library test');
  await page.getByRole('button', { name: 'Typography', exact: true }).click();
  await page.getByRole('textbox', { name: 'Type, then add', exact: true }).fill('SOURCE');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await patterns();
  assert.equal(await library.locator('[data-pattern-card]').count(), 41);
  assert.equal(await library.locator('[data-pattern-card] svg[data-pattern]').count(), 41);
  await library.getByRole('button', { name: 'Custom Pattern', exact: true }).click();
  const layerSelect = library.getByLabel('Pattern design layer', { exact: true });
  const sourceId = await layerSelect.locator('option').nth(1).getAttribute('value');
  await layerSelect.selectOption(sourceId);
  await library.getByRole('button', { name: 'Create Pattern', exact: true }).click();
  await controls.getByLabel('Pattern type', { exact: true }).waitFor();
  assert.equal(await zone.locator(':scope > [data-print-id]').count(), 2, 'Source text must remain editable');
  assert.equal(await controls.getByLabel('Pattern type', { exact: true }).inputValue(), 'custom');
  assert(await svg().locator('image').count() > 0);
  const repeatMarkup = new Set();
  for (const mode of ['grid', 'brick', 'half-drop', 'mirror', 'random']) {
    await controls.getByLabel('Pattern repeat type', { exact: true }).selectOption(mode);
    repeatMarkup.add(await markup());
  }
  assert.equal(repeatMarkup.size, 5);
  await slider('Random position', 64); await slider('Random rotation', 80);
  await slider('Minimum scale', 80); await slider('Maximum scale', 140);
  await slider('Horizontal spacing', 12); await slider('Vertical spacing', 19);
  const beforeRandom = await markup();
  await controls.getByRole('button', { name: 'Randomise pattern', exact: true }).click();
  assert.notEqual(await markup(), beforeRandom);
  assert.equal(await controls.getByLabel('Minimum scale', { exact: true }).inputValue(), '80');
  await slider('Minimum scale', 160);
  assert.equal(await controls.getByLabel('Maximum scale', { exact: true }).inputValue(), '160', 'Scale range cannot invert');
  await controls.getByLabel('Pattern repeat type', { exact: true }).selectOption('grid');
  assert.equal(await controls.getByLabel('Random position', { exact: true }).count(), 0);
  const image = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="40"><path fill="#ff4400" d="M2 2h20v36H2z"/><circle fill="#00aaff" cx="58" cy="20" r="18"/></svg>');
  await library.getByLabel('Upload pattern image', { exact: true }).setInputFiles({ name: 'repeat.svg', mimeType: 'image/svg+xml', buffer: image });
  await library.getByRole('button', { name: 'Replace pattern source', exact: true }).click();
  const originalSource = await svg().locator('image').first().getAttribute('href');
  assert(originalSource.startsWith('data:image/svg+xml;'));
  const types = await controls.getByLabel('Pattern type', { exact: true }).locator('option').evaluateAll(nodes => nodes.map(node => node.value));
  for (const id of types.filter(id => id !== 'custom')) {
    await controls.getByLabel('Pattern type', { exact: true }).selectOption(id);
    assert.equal(await svg().getAttribute('data-pattern'), id);
    assert((await markup()).length > 100, `${id} must render artwork`);
  }
  await controls.getByLabel('Pattern type', { exact: true }).selectOption('camo');
  assert.equal(await controls.locator('input[type="color"]').count(), 3, 'Camo has three additional palette colours');
  await controls.locator('input[type="color"]').first().fill('#123456');
  await slider('Roughness', 80); await slider('Pattern scale', 150); await slider('Pattern amount', 8);
  const camo = await markup();
  await controls.getByRole('button', { name: 'Randomise pattern', exact: true }).click();
  assert.notEqual(await markup(), camo);
  assert.equal(await controls.locator('input[type="color"]').first().inputValue(), '#123456');
  assert.equal(await controls.getByLabel('Pattern scale', { exact: true }).inputValue(), '150');
  await controls.getByLabel('Pattern type', { exact: true }).selectOption('custom');
  assert.equal(await svg().locator('image').first().getAttribute('href'), originalSource, 'Type switching must retain the source');
  await controls.getByLabel('Pattern repeat type', { exact: true }).selectOption('mirror');
  await slider('Pattern rotation', 28); await slider('Pattern opacity', 67);
  await page.getByRole('button', { name: 'Save Asset', exact: true }).click();
  await page.locator('[data-asset-artboard]').waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Asset', exact: true }).click();
  await page.locator('.drag-list-row').getByRole('button', { name: /^Pattern\s/ }).click();
  await patterns();
  assert.equal(await controls.getByLabel('Pattern repeat type', { exact: true }).inputValue(), 'mirror');
  assert.equal(await controls.getByLabel('Pattern rotation', { exact: true }).inputValue(), '28');
  assert.equal(await svg().locator('image').first().getAttribute('href'), originalSource);
  await page.getByRole('button', { name: '← Back to Garment', exact: true }).click();
  await page.getByRole('button', { name: 'Assets', exact: true }).click();
  const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: 'Upload image', exact: true }).click()]);
  await chooser.setFiles({ name: 'existing-upload.svg', mimeType: 'image/svg+xml', buffer: image });
  await zone.locator('img[alt="Artwork"][src^="data:image/svg+xml"]').waitFor();
  await patterns(); await library.getByRole('button', { name: 'Custom Pattern', exact: true }).click();
  const uploaded = library.getByLabel('Pattern uploaded image', { exact: true });
  await uploaded.selectOption(await uploaded.locator('option').nth(1).getAttribute('value'));
  await library.getByRole('button', { name: 'Create Pattern', exact: true }).click();
  assert((await svg().locator('image').first().getAttribute('href')).startsWith('data:image/'));
  const saved = library.getByLabel('Pattern saved asset', { exact: true });
  await saved.selectOption(await saved.locator('option').nth(1).getAttribute('value'));
  await library.getByRole('button', { name: 'Replace pattern source', exact: true }).click();
  assert(await svg().locator('image').count() > 0, 'Asset Builder saved preview is a custom source');
  await controls.getByLabel('Pattern repeat type', { exact: true }).selectOption('random');
  await slider('Random position', 70); await slider('Random rotation', 100); await slider('Pattern amount', 7);
  await slider('Pattern opacity', 73);
  const payload = await library.locator('[data-configured-pattern]').evaluate(node => {
    const dataTransfer = new DataTransfer(); node.dispatchEvent(new DragEvent('dragstart', { bubbles: true, dataTransfer }));
    return dataTransfer.getData('application/x-ceriga-asset');
  });
  const settings = JSON.parse(payload).settings;
  assert.equal(settings.patternRepeat, 'random'); assert.equal(settings.patternCount, 7); assert.equal(settings.opacity, 73);
  assert(settings.patternSource.startsWith('data:image/'));
  const send = async (type, point) => zone.evaluate((node, { type, point, payload }) => {
    const box = node.getBoundingClientRect(), dataTransfer = new DataTransfer();
    dataTransfer.setData('application/x-ceriga-asset', payload); dataTransfer.setData('application/x-ceriga-pattern', 'custom');
    node.dispatchEvent(new DragEvent(type, { bubbles: true, cancelable: true, dataTransfer, clientX: box.x + point.x * box.width, clientY: box.y + point.y * box.height }));
  }, { type, point, payload });
  await zone.scrollIntoViewIfNeeded();
  let body;
  for (const point of [{ x: .5, y: .55 }, { x: .4, y: .6 }, { x: .6, y: .7 }, { x: .5, y: .8 }]) {
    await send('dragover', point); await page.waitForTimeout(80);
    if (await page.locator('[data-pattern-drop-target="base"]').count()) { body = point; break; }
  }
  assert(body, 'Body hover must highlight the exact garment part');
  await send('drop', body);
  const fill = zone.locator('[data-pattern-clip="base"]').last(); await fill.waitFor();
  assert(await fill.evaluate(node => node.style.maskImage.startsWith('url(')));
  assert.equal(await controls.getByLabel('Random position', { exact: true }).inputValue(), '70');
  assert.equal(await controls.getByLabel('Pattern opacity', { exact: true }).inputValue(), '73');
  await page.getByRole('button', { name: 'Shapes and lines', exact: true }).click();
  await page.getByRole('button', { name: 'Custom Area', exact: true }).click();
  const box = await zone.boundingBox();
  const points = [{ x: body.x - .04, y: body.y - .04 }, { x: body.x + .04, y: body.y - .04 }, { x: body.x, y: body.y + .04 }];
  for (const point of [...points, points[0]]) await page.mouse.click(box.x + point.x * box.width, box.y + point.y * box.height);
  await page.getByLabel('Point Type', { exact: true }).selectOption('smooth');
  await page.getByRole('button', { name: 'Flip horizontally', exact: true }).first().click();
  await page.getByRole('button', { name: 'Flip vertically', exact: true }).first().click();
  const areaTransform = await zone.locator('[data-custom-area-transform]').last().getAttribute('transform');
  await send('dragover', body); await page.waitForTimeout(80);
  const target = await page.locator('[data-pattern-drop-target]').getAttribute('data-pattern-drop-target');
  assert.notEqual(target, 'base');
  await send('drop', body);
  const area = zone.locator('[data-custom-area-svg]').last();
  assert((await area.locator('clipPath path').getAttribute('d')).includes(' C '));
  assert.equal(await area.locator('[data-custom-area-transform]').getAttribute('transform'), areaTransform, 'Configured pattern drop preserves target flips');
  assert(await area.locator('image').count() > 0, 'Custom repeat is clipped to editable cubic path');
  await patterns();
  assert.equal(await controls.getByLabel('Pattern repeat type', { exact: true }).inputValue(), 'random');
  assert.equal(await controls.getByLabel('Pattern amount', { exact: true }).inputValue(), '7');
  assert.deepEqual(errors, []);
  console.log('PASS: 42-style gallery, all type switches, live palettes/variation, all custom repeats, scale range, layer/upload/Asset Builder sources, source preservation, save/reopen, configured drag and exact part/Custom Area clipping.');
} finally { await browser.close(); }
