import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors=[]; page.on('pageerror', error=>errors.push(error.message));
  await page.goto(`${process.env.CERIGA_BASE_URL || 'http://127.0.0.1:5189'}/builder/hd-001`);
  await page.getByRole('button',{name:'Continue',exact:true}).waitFor();
  for(let i=0;i<10 && !await page.getByRole('button',{name:'Continue to Review',exact:true}).isVisible();i++) await page.getByRole('button',{name:'Continue',exact:true}).first().click();
  await page.getByRole('button',{name:'Shapes and lines',exact:true}).click();
  await page.getByRole('button',{name:'Custom Area',exact:true}).click();
  const zone=await page.locator('[data-print-design-zone]').boundingBox();
  const click=async(x,y)=>page.mouse.click(zone.x+x*zone.width,zone.y+y*zone.height);
  for(const [i,[x,y]] of [[.35,.3],[.65,.3],[.65,.65],[.35,.65]].entries()) {
    await click(x,y); await page.locator('svg[aria-label="Custom Area in progress"] circle').nth(i).waitFor();
    if(i===0) {
      await page.mouse.move(zone.x+.5*zone.width,zone.y+.4*zone.height);
      assert.equal((await page.locator('svg[aria-label="Custom Area in progress"] polyline').getAttribute('points')).trim().split(' ').length,2,'First anchor must already preview the cursor segment');
    }
  }
  await page.getByRole('button',{name:'Close Path',exact:true}).click();
  const anchors=page.locator('[data-custom-area-point]');
  await anchors.nth(3).waitFor();
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await page.getByRole('button',{name:'Close Path',exact:true}).waitFor();
  assert.equal(await page.locator('svg[aria-label="Custom Area in progress"] circle').count(),4,'Undo closure restores the editable draft');
  await page.getByRole('button',{name:'Redo',exact:true}).click();
  await anchors.nth(3).waitFor();
  const area=page.locator('[data-print-id]').filter({has:page.locator('[data-custom-area-svg]')});
  assert.equal(await area.locator('[data-handles]').count(),0,'Normal transform controls must be hidden while editing');
  const path=()=>page.locator('[data-custom-area-svg] clipPath path').getAttribute('d');
  const center=async locator=>{const b=await locator.boundingBox();return {x:b.x+b.width/2,y:b.y+b.height/2};};
  const drag=async(locator,dx,dy)=>{const p=await center(locator);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+dx,p.y+dy,{steps:8});await page.mouse.up();};
  const undo=async()=>page.getByRole('button',{name:'Undo',exact:true}).click();
  const redo=async()=>page.getByRole('button',{name:'Redo',exact:true}).click();
  const original=await path();
  await page.getByLabel('Point Type',{exact:true}).selectOption('smooth');
  await page.locator('[data-custom-area-handle="0-out"]').waitFor();
  assert((await path()).includes(' C '));
  const smooth=await path();
  await undo(); assert.equal(await path(),original); await redo(); assert.equal(await path(),smooth);
  await drag(page.locator('[data-custom-area-handle="0-out"]'),15,10);
  const linked=await path(); assert.notEqual(linked,smooth);
  await undo(); assert.equal(await path(),smooth); await redo(); assert.equal(await path(),linked);
  await page.getByLabel('Linked Handles',{exact:true}).uncheck();
  const incoming=await center(page.locator('[data-custom-area-handle="0-in"]'));
  await drag(page.locator('[data-custom-area-handle="0-out"]'),12,8);
  const incomingAfter=await center(page.locator('[data-custom-area-handle="0-in"]'));
  assert(Math.hypot(incoming.x-incomingAfter.x,incoming.y-incomingAfter.y)<1,'Unlinked opposite handle stays stationary');
  await page.getByLabel('Point Type',{exact:true}).selectOption('corner');
  assert.equal(await page.locator('[data-custom-area-handle]').count(),0);
  await anchors.nth(0).click(); await anchors.nth(1).click({modifiers:['Shift']});
  const a=await center(anchors.nth(0)),b=await center(anchors.nth(1));
  await drag(anchors.nth(0),12,15);
  const a2=await center(anchors.nth(0)),b2=await center(anchors.nth(1));
  assert(Math.abs((a2.x-a.x)-(b2.x-b.x))<1 && Math.abs((a2.y-a.y)-(b2.y-b.y))<1,'Multi-selected anchors move together');
  const beforeBend=await path();
  const segment=page.locator('[data-custom-area-segment="1"]');
  const middle=await segment.evaluate(node=>{const p=node.getPointAtLength(node.getTotalLength()*.5).matrixTransform(node.getScreenCTM());return {x:p.x,y:p.y};});
  await page.mouse.move(middle.x,middle.y);await page.locator('[data-custom-area-insert]').waitFor();
  await page.mouse.down();await page.mouse.move(middle.x+22,middle.y+8,{steps:8});await page.mouse.up();
  const bent=await path(); assert.notEqual(bent,beforeBend);assert(bent.includes(' C '));
  await undo();assert.equal(await path(),beforeBend);await redo();assert.equal(await path(),bent);
  const midpoint=await segment.evaluate(node=>{const p=node.getPointAtLength(node.getTotalLength()*.5).matrixTransform(node.getScreenCTM());return {x:p.x,y:p.y};});
  const oldBox=await area.boundingBox();
  await page.mouse.move(midpoint.x,midpoint.y);await page.locator('[data-custom-area-insert]').waitFor();await page.mouse.click(midpoint.x,midpoint.y);
  await anchors.nth(4).waitFor();
  const newBox=await area.boundingBox(); assert(Math.abs(oldBox.x-newBox.x)<.1 && Math.abs(oldBox.width-newBox.width)<.1,'Insertion must not reframe the shape or fill');
  await page.locator('[data-custom-area-point="2"]').click();await page.keyboard.press('Delete');
  assert.equal(await anchors.count(),4);assert.equal(await area.count(),1,'Delete removes an anchor, not the area');
  await undo();assert.equal(await anchors.count(),5);await redo();assert.equal(await anchors.count(),4);
  await page.getByRole('button',{name:'Done Editing Path',exact:true}).click();
  assert.equal(await anchors.count(),0);await area.locator('[data-handles]').first().waitFor();
  const retained=await path();
  await page.getByRole('button',{name:'Edit Path',exact:true}).click();await anchors.first().waitFor();assert.equal(await path(),retained);
  await page.keyboard.press('Escape');assert.equal(await anchors.count(),0);
  await page.getByRole('button',{name:'Edit Path',exact:true}).click();
  const setRange=async(name,value)=>page.getByRole('slider',{name,exact:true}).evaluate((input,next)=>{
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,String(next));
    input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));
  },value);
  const flipBefore=await center(anchors.first()), frame=await area.boundingBox();
  await page.getByRole('button',{name:'Flip horizontally',exact:true}).first().click();
  const flipAfter=await center(anchors.first());assert(Math.abs(flipBefore.x+flipAfter.x-2*(frame.x+frame.width/2))<1,'Horizontal flip mirrors the entire path');
  await page.getByRole('button',{name:'Flip vertically',exact:true}).first().click();
  const verticalAfter=await center(anchors.first());assert(Math.abs(flipAfter.y+verticalAfter.y-2*(frame.y+frame.height/2))<1,'Vertical flip mirrors the entire path');
  const width=await page.getByRole('spinbutton',{name:'Width px',exact:true}).inputValue();
  await page.getByRole('spinbutton',{name:'Width px',exact:true}).fill(String(Number(width)+30));
  await page.getByRole('spinbutton',{name:'Width px',exact:true}).press('Tab');await setRange('Rotation',25);
  const transformed=await path(), t0=await center(anchors.first());await drag(anchors.first(),14,8);const t1=await center(anchors.first());
  assert(Math.hypot(t1.x-t0.x-14,t1.y-t0.y-8)<2,'Anchor dragging respects resize, rotation and both flips');
  await undo();
  await page.waitForFunction(expected=>document.querySelector('[data-custom-area-svg] clipPath path')?.getAttribute('d')===expected,transformed);
  assert.equal(await path(),transformed);
  await page.getByLabel('Custom Area texture',{exact:true}).selectOption({label:'Denim'});
  await setRange('Fill scale',140);await setRange('Fill rotation',25);await setRange('Fill opacity',65);
  await page.getByLabel('Custom Area outline',{exact:true}).check();
  await page.getByLabel('Custom Area outline style',{exact:true}).selectOption('dashed');
  assert(await page.locator('[data-custom-area-outline]').getAttribute('stroke-dasharray'));
  await page.getByLabel('Custom Area outline style',{exact:true}).selectOption('dotted');
  assert.equal(await page.locator('[data-custom-area-outline]').getAttribute('stroke-linecap'),'round');
  await page.getByLabel('Custom Area pattern',{exact:true}).selectOption('checks');assert((await path()).includes(' C '));
  assert.equal(await page.getByLabel('Custom Area texture',{exact:true}).inputValue(),'none','Choosing a pattern clears the previous texture');
  await page.getByRole('button',{name:'Done Editing Path',exact:true}).click();
  await page.getByRole('button',{name:'Duplicate',exact:true}).first().click();
  assert.equal(await area.count(),2);assert.equal(await page.locator('[data-custom-area-svg] clipPath path').nth(1).getAttribute('d'),retained,'Duplicate preserves cubic geometry');
  await undo();assert.equal(await area.count(),1);
  await page.getByRole('button',{name:/^back$/i}).last().click();await page.getByRole('button',{name:/^front$/i}).last().click();
  assert.equal(await path(),retained,'Switching garment side retains editable curves');
  await page.getByRole('button',{name:'Assets',exact:true}).click();
  await page.getByRole('button',{name:'+ Create Asset',exact:true}).click();
  await page.getByRole('textbox',{name:'Asset name',exact:true}).fill('Editable curved area');
  await page.getByRole('button',{name:'Shapes and lines',exact:true}).click();
  await page.getByRole('button',{name:'Custom Area',exact:true}).click();
  const artboard=await page.locator('[data-asset-artboard]').boundingBox();
  for(const [index,[x,y]] of [[.25,.25],[.75,.25],[.75,.75],[.25,.75]].entries()) {
    await page.mouse.click(artboard.x+x*artboard.width,artboard.y+y*artboard.height);
    await page.locator('svg[aria-label="Custom Area in progress"] circle').nth(index).waitFor();
  }
  await page.getByRole('button',{name:'Close Path',exact:true}).click();
  await page.getByLabel('Point Type',{exact:true}).selectOption('smooth');
  await page.getByLabel('Linked Handles',{exact:true}).uncheck();
  await page.getByLabel('Custom Area texture',{exact:true}).selectOption('denim-fabric');
  await setRange('Fill rotation',35);
  await page.getByLabel('Custom Area outline',{exact:true}).check();
  await page.getByLabel('Custom Area outline style',{exact:true}).selectOption('dashed');
  const savedPath=await path();
  await page.getByRole('button',{name:'Done Editing Path',exact:true}).click();
  await page.getByRole('button',{name:'Save Asset',exact:true}).click();
  await page.locator('[data-asset-artboard]').waitFor({state:'detached'});
  await page.getByRole('button',{name:'Assets',exact:true}).click();
  await page.getByRole('button',{name:'Edit Asset',exact:true}).click();
  await page.locator('.drag-list-row').getByRole('button',{name:/^Custom Area\s/}).click();
  await page.getByRole('button',{name:'Edit Path',exact:true}).click();
  assert.equal(await path(),savedPath,'Saved asset reopens with original editable cubic anchors');
  await anchors.first().click();
  assert.equal(await page.getByLabel('Linked Handles',{exact:true}).isChecked(),false);
  assert.equal(await page.getByRole('slider',{name:'Fill rotation',exact:true}).inputValue(),'35');
  assert.equal(await page.getByLabel('Custom Area outline style',{exact:true}).inputValue(),'dashed');
  assert.equal(await page.locator('[data-custom-area-texture]').count(),1);
  assert.deepEqual(errors,[]);
  console.log('Passed: closure, linked/independent handles, corners, multi-point move, segment bend/insertion, Delete safety, history, edit-mode transforms, curved fill persistence and guest Asset Builder save/reopen.');
} finally { await browser.close(); }
